name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test on Node ${{ matrix.node }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [18, 20, 22]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Run coverage
        if: matrix.node == 20 && matrix.os == 'ubuntu-latest'
        run: npm run coverage

      - name: Upload coverage
        if: matrix.node == 20 && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
          fail_ci_if_error: false

  security:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run npm audit
        run: npm audit --audit-level=moderate

  package:
    name: Package Verification
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create package
        run: npm pack

      - name: Verify package contents
        run: |
          tar -tzf *.tgz | tee package-contents.txt
          echo "Checking for test files..."
          if tar -tzf *.tgz | grep -E "test/|\.test\.js"; then
            echo "ERROR: Test files found in package!"
            exit 1
          fi
          echo "✅ No test files in package"

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: ephemeral-broker-package
          path: '*.tgz'
